config/routes.rb
Postbox::Application.routes.draw do

  resources :uploads, :only => [:index, :new, :create, :show] do
    resource :metadata, :only => [:show, :edit, :update]
  end
  
  resources :trees, :only => [:index] do
    resources :nodes, :only => [:index]
  end
  
  resources :contacts, :only => [:new, :create]
  
  match '/about' => 'pages#about'
  
  root :to => 'home#index'
  
end

app/models/metadata.rb
class Metadata < ActiveRecord::Base
  belongs_to :upload
  after_initialize :init
  
  validates_presence_of :title, :contact_givenname, :contact_surname, :contact_email, :rights, :license

  def init
    self.license ||= "cc-0"
  end
end

app/controllers/metadata_controller.rb
require 'resque_scheduler'

class MetadataController < ApplicationController
  def show
    @metadata = Metadata.find(:all, :limit => 1, :joins => :upload, :conditions => { :uploads => { :token => params[:upload_id] } }).first
  end

  def edit
    @metadata = Metadata.find(:all, :limit => 1, :joins => :upload, :conditions => { :uploads => { :token => params[:upload_id] } }).first
    if @metadata.upload.tree.status == 3
      flash[:warning] = "Your submission has already been finalized."
      redirect_to upload_path(:id => params[:upload_id])
    end
  end
  
  def update
    @metadata = Metadata.find(:all, :limit => 1, :joins => :upload, :conditions => { :uploads => { :token => params[:upload_id] } }, :readonly => false).first
    if @metadata.update_attributes(params[:metadata])
      @metadata.upload.tree.status = 3
      @metadata.upload.tree.save
      Resque.remove_delayed(Tree, @metadata.upload.tree.id)
      flash[:notice] = "Thank you, #{help.sanitize(@metadata.contact_givenname)}. Your submission has been finalized."
      redirect_to upload_path(:id => params[:upload_id])
    else
      render :action => 'edit', :upload_id => params[:upload_id]
    end
  end
end

app/helpers/metadata_helper.rb
module MetadataHelper
end

app/views/metadata/_form.html.erb
  <%= semantic_form_for @metadata, :url => upload_metadata_path(:upload_id => params[:upload_id]) do |f| %>
    <%= f.inputs "Contact Information" do %>
      <%= f.input :contact_givenname, :label => "Given name", :error_class => 'inline-errors', :input_html => { :size => 50 } %>
      <%= f.input :contact_surname, :label => "Surname", :error_class => 'inline-errors', :input_html => { :size => 50 } %>
      <%= f.input :contact_email, :label => "Email", :error_class => 'inline-errors', :input_html => { :size => 50 } %>
    <% end %>
    <%= f.inputs "Tree Description" do %>
      <%= f.input :title, :error_class => 'inline-errors', :input_html => { :size => 50 } %>
      <%= f.input :project, :error_class => 'inline-errors', :input_html => { :size => 50 } %>
      <%= f.input :abstract, :error_class => 'inline-errors', :input_html => { :cols => 50 } %>
    <% end %>
    <%= f.inputs "Rights & Licensing" do %>
      <%= f.input :rights, :label => "Rights holder(s)", :error_class => 'inline-errors', :input_html => { :size => 50 } %>
      <%= f.input :license, :label => "Creative Commons License", :as => :radio, :collection => ["cc-0", "cc-by", "cc-by-sa", "cc-by-nc", "cc-by-nc-sa"], :error_class => 'inline-errors', :value_as_class => true %>
      <li class="hint">Though required in this form, rights are waived under Public Domain. See <%= link_to "Creative Commons", "http://creativecommons.org/licenses/", :target => "_blank" %> for description of licenses.</li>
    <% end %>
    <%= f.buttons do %>
      <%= f.commit_button "Submit" %>
    <% end %>
  <% end %>

app/views/metadata/edit.html.erb
<% title "Finalize Submission" %>

<%- content_for :content_splash do -%>
<%= content_tag :h2, "Finalize Submission" %>
<%- end -%>

<%= render :partial => 'form' %>

app/views/metadata/show.html.erb
<h3><%=h @metadata.title %></h3>
<p><%=h @metadata.contact_givenname %> <%=h @metadata.contact_surname %> (<%=h @metadata.contact_email %>)</p>
<h3>Abstract</h3>
<p><%=h @metadata.abstract %></p>
<h3>Rights and Licensing</h3>
<p>&#169; <%=h @metadata.rights %></p>
<%= image_tag asset_path("cc_icons/#{@metadata.license}.png"), :alt => @metadata.license %>