config/routes.rb
Postbox::Application.routes.draw do

  resources :uploads, :only => [:index, :new, :create, :show] do
    resource :metadata, :only => [:show, :edit, :update]
  end
  
  resources :trees, :only => [:index] do
    resources :nodes, :only => [:index]
  end
  
  resources :contacts, :only => [:new, :create]
  
  match '/about' => 'pages#about'
  
  root :to => 'home#index'
  
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_one :tree
  has_one :metadata

  attr_accessible :email, :dwc, :dwc_cache
  validates_presence_of :email, :dwc

  mount_uploader :dwc, DarwinCoreUploader
  
  before_create :generate_token
  after_create :create_new_tree
  after_create :create_new_metadata
  
  attr_reader   :darwin_core_data, :name_strings, :dwc_extract, :dwc_tree, :tmp_file

  NAME_BATCH_SIZE = 10_000
  @queue = :dwc_importer
  
  def self.perform(id)
    upload = self.find(id)
    upload.tree.status = 1
    upload.tree.save
    upload.import
  end
  
  def generate_token
    self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
  end
  
  def create_new_tree
    self.create_tree!(:status => 0)
  end
  
  def create_new_metadata
    meta = Metadata.new
    meta.upload = self
    meta.contact_email = self.email
    meta.save(:validate => false)
  end

  def import
    begin
      read_tarball
      update_metadata
      create_root
      store_tree
      #TODO: build nested sets with speed
      #nested_sets
      activate_tree
      send_mail
    rescue RuntimeError => e
      self.tree.status = 99
      self.tree.save
      Node.connection.execute "DELETE FROM nodes WHERE tree_id = #{self.tree.id}"
      send_error_mail
    end
  end

  def read_tarball
    @dwc_extract      = DarwinCore.new(self.dwc.path)
    normalizer        = DarwinCore::ClassificationNormalizer.new(dwc_extract)
    @darwin_core_data = normalizer.normalize(:with_canonical_names => false)
    @dwc_tree         = normalizer.tree
    @name_strings     = normalizer.name_strings
  end
  
  def update_metadata
    if dwc_extract.respond_to?("eml")
      self.metadata.title = dwc_extract.eml.respond_to?("title") ? dwc_extract.eml.title : nil
      self.metadata.abstract = dwc_extract.eml.respond_to?("abstract") ? dwc_extract.eml.abstract : nil
      self.metadata.save(:validate => false)
    end
  end
  
  def create_root
    name = Name.find_or_create_by_name_string("tree_root")
    Node.create!(:parent_id => nil, :tree => self.tree, :name => name)
  end

  def store_tree
    count = 0
    name_strings.in_groups_of(NAME_BATCH_SIZE).each do |group|
      count += NAME_BATCH_SIZE
      group = group.compact.collect do |name_string|
        Name.connection.quote(name_string).force_encoding('utf-8')
      end.join('), (')

      Name.transaction do
        Name.connection.execute "INSERT IGNORE INTO names (name_string) VALUES (#{group})"
      end
    end
    
    @node_id = self.tree.root.id

    @tmp_file = Tempfile.new('dwc', '/tmp')
    begin
      #WARNING: Will not work if more than one worker, would otherwise need composite keys in db
      build_tree(dwc_tree)
      tmp_file.flush
      Node.transaction do
        #WARNING: Hack to accommodate OSX-specific bug in mysql2 gem
        local = (Rails.env == "production") ? "LOCAL" : ""
        File.chmod(0644, tmp_file.path)
        Node.connection.execute "LOAD DATA #{local} INFILE '#{tmp_file.path}' INTO TABLE nodes FIELDS TERMINATED BY '\\t' LINES TERMINATED BY '\\n'"
      end
    ensure
      tmp_file.close
      tmp_file.unlink
    end

  end

  #TODO: accommodate lft and rgt for nested sets as well
  def build_tree(root, parent_id = self.tree.root.id)
    taxon_ids = root.keys
    taxon_ids.each do |taxon_id|

      @node_id += 1
      next unless taxon_id && darwin_core_data[taxon_id]

      parent_id ||= 'NULL'
      name       = Name.find_by_name_string(darwin_core_data[taxon_id].current_name)
      rank       = darwin_core_data[taxon_id].rank

      tmp_file << [@node_id, parent_id, self.tree.id, name.id, taxon_id, rank].join("\t") + "\n"

      build_tree(root[taxon_id], @node_id)
    end
  end
  
  def nested_sets
    Node.rebuild!
  end

  def activate_tree
    self.tree.status = 2
    self.tree.save
  end
  
  def send_mail
    Mailer.preview_email(self).deliver
  end
  
  def send_error_mail
    Mailer.error_email(self).deliver
  end

end

app/controllers/uploads_controller.rb
require 'resque_scheduler'

class UploadsController < ApplicationController

  def index
    page = (params[:page]) ? params[:page] : 1
    @uploads = Upload.includes([:tree, :metadata])
                           .where(:trees => { :status => 3})
                           .paginate(:page => page, :per_page => 15)
                           .order("metadata.updated_at ASC")
  end
  
  def show
    @upload = Upload.find_by_token!(params[:id])
    redirect_url = upload_path :id => @upload.token
    case @upload.tree.status
      when 0
        queue_status = nil
        queue_size = Resque.size(:dwc_importer)
        if  queue_size > 0
          queue_status = "There #{queue_size == 1 ? 'is' : 'are'} #{help.pluralize(queue_size, "job")} in the queue. "
        end
        flash[:notice] = "Your file is queued for processing. #{queue_status}This page will refresh every 15 seconds."
        redirect_with_delay(redirect_url, 15)
      when 1
        flash[:notice] = "Your tree is now processing. This page will refresh every 15 seconds."
        redirect_with_delay(redirect_url, 15)
      when 2
        flash.delete :notice
        flash[:warning] = "Your preview will be cleared in 10 days unless you finalize your submission."
      when 99
        flash.delete :notice
        flash[:warning] = "There was a problem with your file. Check your meta.xml and/or your core file."
    end
  end
  
  def new
    @upload = Upload.new
  end
  
  def create
    @upload = Upload.new(params[:upload])
    if @upload.save
      Resque.enqueue(Upload, @upload.id)
      Resque.enqueue_in(10.days, Tree, @upload.tree.id)
      Mailer.queue_email(@upload).deliver
      redirect_to upload_path :id => @upload.token
    else
      render :action => 'new'
    end
  end

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
  <%= semantic_form_for(@upload, :html => { :multipart => true }) do |f| %>
    <%= f.inputs do %>
      <%= f.input :email, :hint_class => 'upload-hint', :error_class => 'inline-errors', :input_html => { :size => 50 } %>
      <%= f.input :dwc, :as => :file, :label => "Darwin Core Archive"  %>
      <%= f.input :dwc_cache, :as => :hidden %>
    <% end %>
<p class="hint">A description of the Darwin Core Archive format can be found at <%= link_to "GBIF", "http://www.gbif.org/informatics/standards-and-tools/publishing-data/data-standards/darwin-core-archives/", :target => "_blank" %> and example files in their <%= link_to "code repository", "http://code.google.com/p/gbif-ecat/wiki/DwCArchive", :target => "_blank" %>. Accepted file extensions are tar.gz and zip.</p>
    <%= f.buttons do %>
      <%= f.commit_button "Upload" %>
    <% end %>
  <% end %>

app/views/uploads/index.html.erb
<% title "Completed Submissions" %>

<%- content_for :content_splash do -%>
<%= content_tag :h2, "Completed Submissions" %>
<%- end -%>

<table class="uploads">
  <thead>
  <tr>
    <th class="header-user">Contact</th>
    <th class="header-title">Title</th>
    <th class="header-submitted">Submitted</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @uploads.each do |upload| %>
    <tr class="<% row_type = cycle("even", "odd") %><%= row_type %>">
      <td><%=h upload.metadata.contact_surname %>, <%=h upload.metadata.contact_givenname %></td>
      <td><%=h truncate(upload.metadata.title, :length => 50) %></td>
      <td><%= upload.metadata.updated_at.strftime("%b %e at %I:%M%p") %></td>
      <td><%= link_to "Show", upload_path(:id => upload.token) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="clearfix">
  <%= will_paginate @uploads, :class => 'pagination' %>
</div>

app/views/uploads/new.html.erb
<% title "Upload" %>

<%- content_for :content_splash do -%>
<%= content_tag :h2, "Upload" %>
<%- end -%>

<%= render :partial => 'form' %>

app/views/uploads/show.html.erb
<%- if @upload.tree.status < 3 -%>
<%- title "Preview" -%>

  <%- content_for :content_splash do -%>
  <%= content_tag :h2, "Preview" -%>
  <%- end -%>

  <div id="preview-uploader">
  <%- if @upload.tree.status < 3 -%>
    <h3><%=h @upload.email %></h3>
  <%- end -%>
  </div>

<%- elsif @upload.tree.status == 3 -%>

  <%- title "Submission" -%>

  <%- content_for :content_splash do -%>
  <%= content_tag :h2, h(truncate(@upload.metadata.title, :length => 50)) %>
  <h3 class="contact"><%= h(@upload.metadata.contact_surname) %>, <%= h(@upload.metadata.contact_givenname) %></h3>
  <div class="hrDotted"></div>
  <%- end -%>

<%- end -%>

<div id="upload-preview" class="clear">

<div id="tree-nav-wrapper">
  <%- if @upload.tree.status == 3 -%>
  <div id="tabs">
    <ul class="navigation">
      <li><a href="#tree-wrapper">Tree</a></li>
      <li><a href="#metadata">Description</a></li>
    </ul>
    <div id="tree-wrapper">
      <div id="tree"></div>
    </div>
    <div id="metadata">
      <%- if !@upload.metadata.project.empty? -%>
        <h3>Project</h3>
        <div class="metadata-content"><%=h @upload.metadata.project %></div>
      <% end rescue raise ActiveRecord::RecordNotFound%>
      <h3>Abstract</h3>
     <div class="metadata-content"><%=h @upload.metadata.abstract %></div>
    </div>
  </div>
  <%- end -%>

<%- case @upload.tree.status -%>
  <% when 0 %>
    <div id="preview-loader">Waiting in the queue...</div>
  <% when 1 %>
    <div id="preview-loader">Building the preview...</div>
  <% when 2 %>
    <div id="tree-wrapper">
      <div id="tree"></div>
    </div>
<%- end -%>

<%- if @upload.tree.status > 1 && @upload.tree.status != 99 -%>
  <%- content_for :javascript do -%>
    <script type="text/javascript">
    <!--//--><![CDATA[//><!--
    jQuery.extend(TREE, {
      "id"     : "<%= @upload.tree.id %>",
      "root"   : "<%= @upload.tree.root.id %>",
      "status" : "<%= @upload.tree.status %>"
    });
    $.jstree._themes = "/assets/jstree/";
    //--><!]]>
    </script>
  <%- end -%>
<%- end -%>
</div>

<div id="tree-panel-wrapper">
<%- if @upload.tree.statistics && @upload.tree.status > 1 && @upload.tree.status != 99 -%>
<div id="tree-stats" class="panel">
  <h3>Basic Statistics</h3>
<ul>
<%- @upload.tree.statistics.each do |type,stat| -%>
<%= content_tag :li, type.to_s.humanize << ": " << stat.to_s.gsub(/(\d)(?=\d{3}+(?:\.|$))(\d{3}\..*)?/,'\1,\2') %>
<%- end -%>
</ul>
</div>
<%- if @upload.tree.status == 2 -%>
  <%= button_to "Finalize Submission", edit_upload_metadata_path({:upload_id => @upload.token}), :method => :get, :class => "update" %>
<%- elsif @upload.tree.status == 3 -%>
<div id="tree-download" class="panel">
  <div><%= image_tag(asset_path("cc_icons/#{@upload.metadata.license}.png")) %></div>
  <%- if @upload.metadata.license != "cc-0" -%>
    <div>&copy; <%=h @upload.metadata.rights %></div>
  <% end %>
  <div><%= link_to "Download", @upload.dwc.url %></div>
</div>
<%- end -%>
<%- end -%>
</div>

</div>