config/routes.rb
Postbox::Application.routes.draw do

  resources :uploads, :only => [:index, :new, :create, :show] do
    resource :metadata, :only => [:show, :edit, :update]
  end
  
  resources :trees, :only => [:index] do
    resources :nodes, :only => [:index]
  end
  
  resources :contacts, :only => [:new, :create]
  
  match '/about' => 'pages#about'
  
  root :to => 'home#index'
  
end

app/helpers/layout_helper.rb
module LayoutHelper  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<div id="Footer" class="structural fixedWidth">
  <div class="inner">
      <span><%= link_to 'Global Names Architecture', 'http://www.globalnames.org' %></span>|
      <span><%= link_to 'Global Names Index', 'http://gni.globalnames.org' %></span>|
      <span><%= link_to 'Global Names Classification and List Repository', 'http://gnaclr.globalnames.org' %></span>|
      <span><%= link_to 'Global Names Integrated Taxonomic Editor', 'http://gnite.org' %></span>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="Header" class="structural fixedWidth">
  <div class="inner">
    <div id="Logo">
      <a href="/">
        <h1>Global Names PostBox</h1>
      </a>
    </div>
    <ul id="SiteNavigation">
      <%- if controller_name == "home" -%>
        <li class="active"><%= link_to "Home", root_path %></li>
      <%- else -%>
        <li><%= link_to "Home", root_path %></li>
      <%- end -%>
      <%- if controller_name == "uploads" && action_name == "new" -%>
        <li class="active"><%= link_to "Upload", new_upload_path %></li>
      <%- else -%>
        <li><%= link_to "Upload", new_upload_path %></li>
      <%- end -%>
      <%- if controller_name == "uploads" && action_name == "index" -%>
        <li class="active"><%= link_to "Browse", uploads_path %></li>
      <%- else -%>
        <li><%= link_to "Browse", uploads_path %></li>
      <%- end -%>
      <%- if controller_name == "pages" && action_name == "about" -%>
        <li class="active"><%= link_to "About", about_path %></li>
      <%- else -%>
        <li><%= link_to "About", about_path %></li>
      <%- end -%>
      <%- if controller_name == "contacts" -%>
        <li class="active"><%= link_to "Contact", new_contact_path %></li>
      <%- else -%>
        <li><%= link_to "Contact", new_contact_path %></li>
      <%- end -%>
    </ul>
  </div>
</div>

app/views/layouts/_javascript.html.erb
<% if content_for?(:javascript) %>
  <%= yield :javascript %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? "Global Names PostBox :: " << content_for(:title) : "Global Names PostBox" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <% if @redirect_url %>
    <meta http-equiv='refresh' content='<%= @redirect_delay -%>;url=<%= @redirect_url -%>'>
  <% end %>
</head>
<body>
  <div id="SiteContainer" class="structural">

    <div class="background"></div>

    <%= render :partial => 'layouts/header' %>

   <div id="BodyContent" class="structural fixedWidth clear">
     <div class="inner">
       <div id="content-wrapper">
         <%- flash.each do |name, msg| -%>
           <%= content_tag :div, msg, :id => "flash_#{name}" %>
         <%- end -%>
         <%- if content_for?(:content_splash) -%>
           <div id="content-splash">
             <%=  content_for(:content_splash) %>
           </div>
         <%- end -%>
         <div id="content-body">
           <%= yield %>
         </div>
         <%- if content_for?(:content_features) -%>
           <div id="content-features" class="clear">
             <%= content_for(:content_features) %>
           </div>
         <%- end -%>
       </div>
     </div>
   </div>

   <%= render :partial => 'layouts/footer' %>

  </div>
  <%= render :partial => 'layouts/javascript' %>
</body>
</html>